### ISSUE TITLE
Routerliste anpassen

### ISSUE THREAD

**Issue by ghost** [Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io#1]
Hey olli,

bitte die Routerliste anpassen. Derzeit supporten wir mit unserer neuen Firmware nur

841N/ND
842N/ND
WDR3600
NanoStation M2/M5
NanoBeam

**Comment by Olli** [comment]
NanoBeam - NBE-M2-13 oder NBE-M5-16 oder NBE-M5-19 oder alle 3?

**Comment by ghost** [comment]
Alle 3
Am 25.08.2015 17:40 schrieb "Olli" notifications@github.com:

**Comment by Olli** [comment]
k
