### ISSUE TITLE
842n/842nd auflisten bitte

### ISSUE THREAD

**Issue by ghost** [Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io#13]
http://www.freifunk-waldheim.de/mitmachen/

bitte die 842N und ND auflisten und verlinken danke

**Comment by Olli** [comment]
N ist auf amazon nicht Verfügbar. Amazonlink erstmal weggelassen.

**Comment by ghost** [comment]
Danke

----- Ursprüngliche Nachricht -----
Von: "Olli" notifications@github.com
Gesendet: ‎15.‎09.‎2015 17:15
An: "Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io" Freifunk-Mittelsachsen.github.io@noreply.github.com
Cc: "davidnoelte" dnoelte@gmail.com
Betreff: Re: [Freifunk-Mittelsachsen.github.io] 842n/842nd auflisten bitte(#13)

Closed #13.

**Comment by ghost** [comment]
das ganze brauchen wir aber auch auf freifunk-waldheim.de :-) soll ich dir da extra nen ticket machen?
