### ISSUE TITLE
neue router mit aufnehmen

### ISSUE THREAD

**Issue by ghost** [Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io#16]
http://www.amazon.de/TP-Link-TL-WR1043ND-Ultimate-Anschluss-Glasfasermodem/dp/B002YETVTQ/ref=sr_1_5?s=computers&ie=UTF8&qid=1442408547&sr=1-5&keywords=841nd

http://www.amazon.de/TP-Link-TL-WDR4300-Simultan-Dual-Band-LAN-Ports/dp/B00810P80S/ref=sr_1_1?s=computers&ie=UTF8&qid=1442408637&sr=1-1&keywords=tp-link+4300

**Comment by ghost** [comment]
CPE510 und CPE210 auch bitte mit aufnehmen

**Comment by Olli** [comment]
sind drin

**Comment by ghost** [comment]
bitte M2 Loco hinzufügen und Bullet M zu der liste
raus soll dafuer der CPE510 (warum erzaehl ich dir spaeter)
und den nanobeam auch raus. der laeuft nicht stabil

**Comment by Olli** [comment]
nächste mal bitte neue issue aufmachen

**Comment by Olli** [comment]
ach ja und erledigt :)
