### ISSUE TITLE
VIMO Video selber hosten

### ISSUE THREAD

**Issue by Olli** [Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io#17]
-> weniger javagescripte -> schnellere seite

**Comment by ghost** [comment]
Müssen wir mal ausdiskutieren. Bin ich weniger von angetan. Vimeo ist halt für Video  optimiert.

----- Ursprüngliche Nachricht -----
Von: "Olli" notifications@github.com
Gesendet: ‎20.‎09.‎2015 19:05
An: "Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io" Freifunk-Mittelsachsen.github.io@noreply.github.com
Betreff: [Freifunk-Mittelsachsen.github.io] VIMO Video selber hosten (#17)

-> weniger javagescripte -> schnellere seite

**Comment by Olli** [comment]
ok erst mal auf yt geändert - ggf läuft es schneller. mehr videoformate werden unterstützt
