### ISSUE TITLE
Netzausbau mit Heatmap

### ISSUE THREAD

**Issue by Olli** [Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io#3]
Heatmapjszeug auf Netzausbau einbauen
csv2json script basteln.

**Comment by ghost** [comment]
willst du das direkt in die seite mit integrieren? Ich wäre ja für eine extra seite dafür oder wie siehst du das?
bzw. ne subdomain map.freifunk-waldheim.de falls man die daten auch von wo anders reinpullen will.

**Comment by ghost** [comment]
ok haben das ja im chat besprochen ich bau dir ne api wo du die heatmap daten als json bekommst.
ausserdem wird auf dem server nächtlich die csv daten von den scans gepullt und daraus json für dich dann generiert.

**Comment by Olli** [comment]
netzausbau ist erst mal soweit auf der jetzigen karte zu sehen

**Comment by Olli** [comment]
Heatmap ist kompliziert weil Datennormalisierung -> dauert länger weil ich mich mit dem Thema mal in einer günstigen Minute beschäftigen muss.

**Comment by Olli** [comment]
problem muss anders angefasst werden
