### ISSUE TITLE
Endgeräte bitte auf Amazon verlinken

### ISSUE THREAD

**Issue by ghost** [Freifunk-Mittelsachsen/Freifunk-Mittelsachsen.github.io#5]
hey olli,
kannst du bitte die endgeräte auf amazon verlinken das die leute die schneller kaufen können?

http://www2.freifunk-waldheim.de/mitmachen/

**Comment by Olli** [comment]
3bdfbceaeea0bdc3c7284681aeb4083d896c65d1
